### ISSUE TITLE
Setting sidebar menu to collapse hides all menu items

### ISSUE THREAD

**Issue by mgibson323** [LisaFC/justdocs#1]
When I change `sidebar_menu_compact` to `true`, it causes all submenu items to disappear from the menu. You can see an example here: 

https://github.com/mgibson323/test-justdocs

Screenshot: 

![Screen Shot 2020-05-11 at 10 21 48 AM](https://user-images.githubusercontent.com/4676632/81591412-3f407d80-9371-11ea-962e-d41ac25776d2.png)

I've made no changes to partials/sidebar-tree.html or any other files, aside from setting `sidebar_menu_compact` to `true`in config.toml

**Comment by mgibson323** [comment]
Hi! Any updates on this issue?

**Comment by LisaFC** [comment]
Hi Michael! Sorry I missed this, it's kind of a spinoff from my main project so I don't check the issues as frequently. What version of Hugo are you using, there was a weird bug a while back that broke our left nav but was fixed in a subsequent version.

You may also want to update the Docsy submodule to a more recent version.

**Comment by mgibson323** [comment]
Hi @LisaFC - thank you! I was running 0.62.2 locally but when I updated to the current release the menu did indeed work properly. I will close this issue, thank you!
